### ISSUE TITLE
Grid not drawn completely

### ISSUE THREAD

**Issue by diethardsteiner** [HiromuHota/pentaho-kettle#101]
When opening a job or transformation, the grid is shown in the visible area, also a bit when scrolling down, but once scrolling further down, it disappears:
![screenshot from 2018-03-29 09-44-02](https://user-images.githubusercontent.com/1726057/38079153-2361483a-3336-11e8-9c16-bd580ae82a57.png)

Mozilla, Fedora 27

**Comment by HiromuHota** [comment]
Thank you for reporting a bug, but can you tell me the version of webSpoon you were using?
I guess you were using 0.8.0.14 or before when you had this issue, right?
As you may have noticed, the drawing grid has changed at 0.8.0.15, where the grid is drawn only when you enable it and you are dragging a step/job entry.
So yes, it was a bug up until 0.8.0.14, but it has been eventually resolved at 0.8.0.15. Please upgrade it.

**Comment by diethardsteiner** [comment]
I downloaded a latest version some time ago. Today I checked with 0.8.0.15: Following problems:
- Grid not shown although ticked in Options
- Repository Button missing
![screenshot from 2018-04-02 13-33-18](https://user-images.githubusercontent.com/1726057/38215873-0082ac4e-36c1-11e8-87fb-f51fb1a99c45.png)


Firefox Quantum 57.0.4 (64-bit)

**Comment by HiromuHota** [comment]
- Grid not shown although ticked in Options

Sorry for the confusion, but this is the expected behaviour.
The grid is only drawn when you are dragging a step.
Due to a technical reason, this has to be like this unless there is a better way.

- Repository Button missing

I tested with 0.8.0.15-full and FF 59.0.2 and confirmed that the repository button was there.
I believe you were using 0.8.0.15-full instead of 0.8.0.15, which does not have any plugin hence no repository button.
For some reason, the repository button goes missing on very rare occasions. Deleting the Karaf cache and restarting the Tomcat would resolve the issue.

**Comment by diethardsteiner** [comment]
Ok, thanks for letting me know! I'll make sure I'll use the full version next time.

**Comment by HiromuHota** [comment]
Since most of the users, I think, use full version, maybe it's time to change the tag naming convention.
Now
0.8.0.15 for without plugin, 0.8.0.15-full for with plugins.
Future?
0.8.0.15 for with plugin and 0.8.0.15-full for with plugins (for backward compatibility).

**Comment by diethardsteiner** [comment]
Don't worry, it was just my mistake. Yes, indeed, the repository is a plug-in as well ... I failed to remember this.

**Comment by HiromuHota** [comment]
The naming convention for the Docker image tag has changed. See https://github.com/HiromuHota/webspoon-docker#tags for how it's changed.
