### ISSUE TITLE
Scheduler Jobs in Spoon Web

### ISSUE THREAD

**Issue by tduartez** [HiromuHota/pentaho-kettle#105]
## Expected Behavior

Hi, I need to raise a Spoon Web  in SAP CLOUD but I need to schedule the JOBS and transformation with the SAP Scheduler, is this possible? Is it possible to schedulate the JOBS using Spoon Web in the Cloud?

## Actual Behavior
Screenshots and error messages are helpful.

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Server
  - OS (e.g., Mac OS X 10.12.6):
  - Java (e.g., Oracle JDK 8u151):
  - Servlet container (e.g., Apache Tomcat 8.5.20):
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b):

### Client
  - OS (e.g., Mac OS X 10.12.6):
  - Browser (e.g., Google Chrome 64.0.3282.140):

**Comment by HiromuHota** [comment]
I can see two questions:
1.  I need to schedule the JOBS and transformation with the SAP Scheduler, is this possible?
1.  Is it possible to schedulate the JOBS using Spoon Web in the Cloud?

For the 1st question, I'm not familiar with the SAP Scheduler so I'm not so sure but I'd doubt it. Pentaho Community (now known as Vantara Community) or SAP community, I'm not sure if it exists, would be the best place to ask this question.

For the 2nd question, no and yes.
No, because webSpoon is based on CE version of PDI/Spoon and CE does not include the job scheduler. This is only available in EE (see [here](https://help.pentaho.com/Documentation/5.4/0L0/0Y0/060) for more details about the job scheduler).
Yes, you could "technically" upgrade webSpoon to EE by copying things like Jar files from EE to webSpoon, but I do not support this operation (i.e., do it at your own cost and risk).

**Comment by tduartez** [comment]
Hi Hiromu, thank you so much

Regards

*Teresa Duartez Uribe*



2018-05-23 14:28 GMT-03:00 Hiromu Hota <notifications@github.com>:
