### ISSUE TITLE
Help!!!!! Can not connect to DataBase

### ISSUE THREAD

**Issue by shashaaixinpei** [HiromuHota/pentaho-kettle#109]
Hi all, when I use webSpoon to create database connection to connect mysql database, there is a error as follow:

**Error connecting to database [test] :org.pentaho.di.core.exception.KettleDatabaseException: 
Error occurred while trying to connect to the database

Driver class 'org.gjt.mm.mysql.Driver' could not be found, make sure the 'MySQL' driver (jar file) is installed.
org.gjt.mm.mysql.Driver**

Then I add the jar file:mysql-connector-java-5.1.46.jar to $CATALINA_HOME/lib/, but it is useless.
my system and soft are as follows:
(1)win10 64bit
(2)docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
（3）mysql5.7

**Comment by HiromuHota** [comment]
1. What’s the version of webSpoon?
2. Did you restart webSpoon (the server side, not client/browser side) after adding mysql jar?




________________________________

**Comment by HiromuHota** [comment]
Please try `mysql-connector-java-5.1.46-bin.jar` instead of `mysql-connector-java-5.1.46.jar`.

**Comment by shashaaixinpei** [comment]
I try it, but there is another error:
Error connecting to database: (using class org.gjt.mm.mysql.Driver)
Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago,the driver has not received any packets from the server

**Comment by HiromuHota** [comment]
The error message you got means that the JDBC driver is working, but not able to access your mysql server.
According to your first comment, looks like you use different Docker hosts: one host for webSpoon and another for MySQL.
Please make sure that
- The mysql port (3306) is bind to the host and is accessible from outside of the host.
- The mysql bind-address is something like 0.0.0.0

Now the issue is not related to webSpoon, it is more like how to access a Dockerized mysql.
It'd be better to find answers in a site like https://hub.docker.com/_/mysql/.

**Comment by shashaaixinpei** [comment]
Thank you very much，I will try again.

**Comment by HiromuHota** [comment]
Close assuming it's been solved.
