### ISSUE TITLE
Blank page after deploying to BA server tomcat

### ISSUE THREAD

**Issue by ankit0611** [HiromuHota/pentaho-kettle#15]
I deployed latest spoon.war into webapps directory of tomcat under BA server installation and after restarting tomcat i am trying to open **http://localhost:8080/spoon** but its opeing only **bank page** nothing else.

Kindly help me understand what i am doing wrong.

**Comment by HiromuHota** [comment]
Hi Ankit, thank you for reporting an issue. Let me help you identify what went wrong.
The latest spoon.war means ver. 0.6.1.4, please correct me if it is wrong.

First, please tell me about your environment:
- Version of BA server (e.g., CE 6.1.0.1)
- Java version (e.g., Oracle Java 8u101)
- Host OS and its version (e.g., Windows 10 Professional 64 bits)

Then,
- Does this issue happen only on the latest version of webSpoon? Did you try earlier versions and the same result?
- Can you see the Pentaho User Console when you try to open http://localhost:8080/ ?

Finally, if you don't mind, please copy and paste the log of Tomcat (`tomcat/logs/catalina.out`), but please delete any confidential information from the log.

**Comment by ankit0611** [comment]
Hi Hiromu,

Thanks for the prompt reply. Yes latest means ver. 0.6.1.4
Version of BA Server EE 6.0.1.0.386
Java version jdk 1.8.0_73
Host OS windows 7 professional 64 bits

No this is first time i am going to try any version of webspoon.
Yes Pentaho user consol is visible and working fine.


[catalina.2017-01-03.txt](https://github.com/HiromuHota/pentaho-kettle/files/684206/catalina.2017-01-03.txt)

**Comment by HiromuHota** [comment]
I was able to reproduce this symptom with IE8, which is the default version in Windows 7, but not supported by RAP/RWT. See [here](http://www.eclipse.org/rap/noteworthy/3.0/) for the detail.
What is your browser? If you use IE8, please use IE9+ or other supported browsers.
![virtualbox_windows 7_04_01_2017_10_20_18](https://cloud.githubusercontent.com/assets/20668349/21653882/2b4a96a8-d268-11e6-9d15-191e59f6f438.png)

**Comment by ankit0611** [comment]
I am using IE11 and chome 55. It's supported as per the RAP 3.0 link provided by you. What else i can try?

**Comment by HiromuHota** [comment]
Yes, these browsers are supported.
Then, I want to make sure I correctly understand what the blank page means. Can you take a screenshot of your blank page and upload to here?

2017/01/05 0:48、Ankit Srivastava <notifications@github.com<mailto:notifications@github.com>> のメッセ`ジ:


I am using IE11 and chome 55. It's supported as per the RAP 3.0 link provided by you. What else i can try?

―

**Comment by ankit0611** [comment]
Yes. Here is it.
![untitled](https://cloud.githubusercontent.com/assets/14798755/21685777/312e2c50-d363-11e6-9377-4d60d46ad360.png)

**Comment by HiromuHota** [comment]
I found out that it was because of the Tomcat version.
CE/EE 6.0 comes with Tomcat of 8.0.24.0, CE/EE 6.1 comes with Tomcat of 8.0.33.0.
According to my tests, webSpoon only works with 8.0.30.0 or higher.
I tried to figure out which change between 8.0.29.0 and 8.0.30.0 was critical, but not found yet.
Note that I only tested on 8.0.X between 8.0.24.0 and 8.0.33.0, I haven't tested on other versions of Tomcat and not investigated the version compatibility of Jetty and other servlet containers.

For the moment, please try with 6.1 (CE or EE) or a vanilla (not with Pentaho) Tomcat of 8.0.30.0 or higher.
Sorry for the inconvenience and thank you for giving me a chance to make it better.

**Comment by HiromuHota** [comment]
I'm still in the middle of investigation. I thought it was because of the version of Tomcat, but it was not.
Your symptom is different from the one I had with IE8: the page is white in your case.
I also had the same symptom as yours during my tests, but it's gone when I restarted Tomcat.
So I suspect there is a race condition in the plugin loading or somewhere.
Did you try to restart Tomcat? Does this issue happen every time you restart it?

**Comment by ankit0611** [comment]
Yes. I tried restarting tomcat several times and it happens each of the time.

**Comment by HiromuHota** [comment]
Can you add a slash at the end and try `http://localhost:8080/spoon/` instead of `http://localhost:8080/spoon`?

**Comment by ankit0611** [comment]
:) that solves it. Thanks a lot.

**Comment by HiromuHota** [comment]
I'm glad the issue was solved.

Here is the reason behind the scene:
CE/EE 6.0 comes with Tomcat of 8.0.24.0, CE/EE 6.1 comes with Tomcat of 8.0.33.0.
According to the [change log](http://tomcat.apache.org/tomcat-8.0-doc/changelog.html), Tomcat's behavior for redirect has changed in 8.0.30 in a way that `http://localhost:8080/spoon` is redirected to `http://localhost:8080/spoon/` in 8.0.30+.
I will update the README accordingly.
