### ISSUE TITLE
I can't choose language.

### ISSUE THREAD

**Issue by chenxiaoliang0901** [HiromuHota/pentaho-kettle#158]
## I can't choose language.

hello，I want to choose language,but It's grey.

**Comment by HiromuHota** [comment]
The language has been greyed out and cannot be chosen on web UI to prevent end-users from changing it.
To change it, please create a file at `~/.kettle/.languageChoice` with the following content:
```
LocaleDefault=en_US
```
then change `en_US` with your preferred locale (e.g., `zh-CN`).

**Comment by chenxiaoliang0901** [comment]
I revised kettle's index.html in Chinese, but it was scrambled. How can I solve it?

**Comment by chenxiaoliang0901** [comment]
I tried your method,  LocaleDefault=zh_CN ，but still showed English.

**Comment by HiromuHota** [comment]
My previous reply contains a typo.
wrong: `LocaleDefault=zh-CN` (hyphen)
correct: `LocaleDefault=zh_CN` (underscore)
But I don't think this typo affects you because seems like you already noticed it.

To make the change effective, please restart the webSpoon server.
Also make sure to create `~/.kettle/.languageChoice` in the server side. If webSpoon is deployed as a Docker container, `~/.kettle/.languageChoice` within the container should be created.

The scrambled index.html is a different problem.
I can take a look if you can share the index.html.

**Comment by chenxiaoliang0901** [comment]
Thank you very much. I've settled it.

**Comment by HiromuHota** [comment]
You're very welcome :)

**Comment by coderdream** [comment]
1. use docker ps command  to get container id;
2. use docker inspect 5bb04abad45d command to get MergedDir
3. enter MergedDir and get in home/tomcat/.kettle directory;
4. create .languageChoice
5. restart container

![image](https://user-images.githubusercontent.com/1549511/187884678-35f32eaa-bdd6-4f4b-9dbd-625e4b0b50c2.png)

![image](https://user-images.githubusercontent.com/1549511/187884925-9c48d92e-7254-475a-aeed-879ba282c5a8.png)
