### ISSUE TITLE
webspoon-Generic database error(presto)

### ISSUE THREAD

**Issue by GirishAthanikar** [HiromuHota/pentaho-kettle#165]
Hi Hiromu,
Hope your doing good !
When we are running **job** and **transformation** using webspoon, So by using **pentaho engine**, it's running as expected but the same when we are running through **spark engine** we are getting an error stating that **"Driver class 'io.prestosql.jdbc.PrestoDriver' could not be found, make sure the 'Generic database' driver (jar file) is installed"**.

Looking forward for your input and advise on the same.

Thanks,
Girish
![presto-error-generic-db](https://user-images.githubusercontent.com/46562786/60942132-23a6b980-a2ff-11e9-88d6-24c1288d8f99.PNG)

**Comment by HiromuHota** [comment]
Thanks for reporting!
The issue sounds similar to https://github.com/HiromuHota/pentaho-kettle/issues/85 because
- Works fine with PDI engine but not on Spark.
- JDBC driver related

Let me look into this when I have time.

**Comment by HiromuHota** [comment]
I tested myself using a Dockerized Presto (https://hub.docker.com/r/starburstdata/presto) and it worked.
Here is how I figured.

1. Place [presto-jdbc-0.221.jar](https://repo1.maven.org/maven2/com/facebook/presto/presto-jdbc/0.221/presto-jdbc-0.221.jar) at `$CATALINA_HOME/lib` as described at https://github.com/HiromuHota/pentaho-kettle#third-party-plugins-and-jdbc-drivers
1. Use `com.facebook.presto.jdbc.PrestoDriver` instead of `io.prestosql.jdbc.PrestoDriver` as custom driver class name.

![image](https://user-images.githubusercontent.com/20668349/61418903-fc2c8f80-a8b0-11e9-9383-7b4132e736ed.png)

**Comment by HiromuHota** [comment]
Close as I heard from @GirishAthanikar that he's resolved it himself.

**Comment by GirishAthanikar** [comment]
Hi Hiromu,
Hope your doing good !
Thanks for looking into this issue and i tried above you mentioned solution of generic DB(Presto) and its working fine. So both solutions are working for my requirement.

Thanks,
Girish
