### ISSUE TITLE
Pentaho, Spring and Form based authentication.

### ISSUE THREAD

**Issue by usbrandon** [HiromuHota/pentaho-kettle#76]
You are an exceptionally gifted person at Pentaho with a deep enough understanding of Spring and Authentication mechanisms applied to Pentaho products to answer this topic. For the longest  time (customer in 2010), including now; Pentaho ships EE and CE servers with PUCLogin.jsp that is using BASIC authentication.  This created no end of hassle when using CDE dashboards and letting the session timeout.  The browser would then ask for credentials twice.  After some research, it seems that FORM based authentication would be / is recognized to be a much better standard to follow.

What must change about the Pentaho Server or Webspoon's spring configuration to use this authentication type that deals with the stateless nature of browser traffic and the potential session loss that happens server side.  I imagine Webspoon will hit this problem much sooner than  users  of the BI Server due to the potentially long running nature of KJB and KTR files.  I have not tried to do a long running transformation using Webspoon; but believe in the principal of "We get what we inspect, not what we expect."  Hopefully this problem can be avoided by your awesome tool.

I have a case open with EE Support, but it is very slow going. I see this more of a design issue.  I continue to be surprised by the lack of attention to authentication and authorization in the platform. Even the dialogs that handle user details do not resize or scroll properly.

Specifically I am looking for what a solution strategy looks like. I imagine that the right Spring beans need to be wired and configured and the login screens (PUCLogin.jsp) and login dialogs need to change the java code to use FORM auth instead of BASIC. (Especially bad is passing credentials over a URL as parameters.)

http://jira.pentaho.com/browse/BISERVER-13648

Where someone gets into the issue:
https://stackoverflow.com/questions/2180206/how-to-force-jetty-to-ask-for-credentials-with-basic-authentication-after-invali

In 2014 Pentaho Developers published this wiki outlining other authentication methods.
http://wiki.pentaho.com/display/ServerDoc2x/Authentication+from+Third-Party+Applications

IBM's code here looks like it approaches some version of what needs to happen in Pentaho applications.
https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.iseries.doc/ae/tsec_pofolo.html

Thanks for any pointers.  I admire your work.

**Comment by usbrandon** [comment]
I managed to come across an updated approach to logging.  These guys created a useful custom login plugin for 5.x which works with 7.x in the dev branch.  Still have to test and see what distance this goes to fixing the session timeout issue, but i suspect the same mechanism would be helpful for webspoon.
https://github.com/marpontes/tapa/tree/dev

**Comment by HiromuHota** [comment]
Hi Brandon,
Thank you for your compliment.

Both authentication and authorization are important for webSpoon too, especially when it is used by multiple users.
However, I haven't spent enough time on these so far because there were more basic things to do (e.g., UI, repository connection, etc).

For the matter of BASIC or FORM auth, here is my understanding:
- It is FORM if you access http://localhost:8080/pentaho (will be redirected to http://localhost:8080/pentaho/Login)
- It is BASIC if you access http://localhost:8080/pentaho/api/repos/..... (as reported in BISERVER-13648)
- I 'think' it is based on the url pattern for which auth method is used.

As you pointed out, it is a design matter in a way: which auth method you use for which url pattern, so I'd let the support team handle it.

webSpoon, on the other hand, has only one endpoint (http://localhost:8080/spoon/spoon), so the double login issue (BISERVER-13648) would not happen.
Of course you have to login again when a session expires. If you can't be bothered by frequent re-logins, I'd make the session-timeout longer.

When I was using the pentaho server by myself, I edited `webapps/pentaho/WEB-INF/web.xml` and changed the value from 120 to 0 so that the session never expires.
```
  <session-config>
    <session-timeout>120</session-timeout>
  </session-config>
```
It was OK because I was the only user for that server, but the session-timeout should be expired after some finite time when the server is shared.

I don't think I've answered for what you are looking for, but I hope it'd help you in some way.
