### ISSUE TITLE
which method is appropriate for writing GUI for steps

### ISSUE THREAD

**Issue by nazeri84** [HiromuHota/pentaho-kettle#82]
Hi
I need to write gui for new steps in webspoon and I know the default method is using the swt, but I want to know whether is it possible to use swing instead of swt ?
if yes, could you please tell me how , if no what is another option.
thanks for your consideration.

**Comment by HiromuHota** [comment]
I haven't tried to use Swing in Spoon or in webSpoon before, but theoretically Swing should work in webSpoon.
You should try your Swing UIs in Spoon first ([This doc](http://www.eclipse.org/articles/article.php?file=Article-Swing-SWT-Integration/index.html) may help you doing that), then you can try these UIs in webSpoon.
If they work in Spoon but they do not in webSpoon, please let me know. I'm happy to help you.

Having said, I'd recommend against using Swing in webSpoon due to
1. not common in Spoon hence not so many example code
2. a time-lag concern: when you open a dialog that has Swing UIs in webSpoon, you might feel some lag until the dialog to pop up.

Swing is written purely in Java unlike SWT. One of the main differences between Swing and SWT is where UI is rendered. In Swing UIs are rendered by Java, while in SWT they are rendered by native OS libraries (that's why you have different SWT jar for Windows, Mac OS X, Linux).
webSpoon uses RWT in place of SWT. RWT is a nearly-SWT-compatible UI widget for web app, meaning it takes a server-client architecture. RWT UIs are rendered in the client side in HTML and CSS based on the (meta)data sent from the server side.
I think that Swing UIs in webSpoon are rendered by Java in the server side, the rendered image is transferred via HTTP to the client side. You can imagine the data size of image is bigger than that of metadata. This would result in the time-lag when opening the dialog that has Swing UIs. I don't know how severe the impact would be. It might be negligibly small.

**Comment by nazeri84** [comment]
thanks for your answer and your consideration.
